### ISSUE TITLE
<HIGH+1><INTEGRATION> Need pure-wheel of "materialsproject new api" client

### ISSUE THREAD

**Issue by kimo** [PySheets/pysheets#107]
Here is the python module.

https://github.com/materialsproject/api
**mp_api**

Error in pysheets
```
class.js:82 Uncaught (in promise) Error: Traceback (most recent call last):
  File "/lib/python3.12/site-packages/micropip/_commands/install.py", line 146, in install
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for: 'pymatgen!=2024.2.20,>=2022.3.7', 'pymatgen>=2024.6.10', 'pyzmq>=25.1.1', 'pymongo>=4.2.0', 'sentinels'
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package
```

Error in pydiode console
```
Welcome to the Pyodide 0.26.2 terminal emulator 🐍
Python 3.12.1 (main, Jul 26 2024 14:03:47) on WebAssembly/Emscripten
Type "help", "copyright", "credits" or "license" for more information.
>>> import micropip
>>> await micropip.install("mp_api", keep_going=True)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.12/site-packages/micropip/_commands/install.py", line 146, in install
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for: 'pymatgen!=2024.2.20,>=2022.3.7', 'pymatgen>=2024.6.10', 'pyzmq>=25
.1.1', 'pymongo>=4.2.0', 'sentinels'
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package
>>> 
```` 

@laffra @sangramsingh-kss

**Comment by kimo** [comment]
This belongs to the pyodide project. Hence closing this here.

**Comment by laffra** [comment]
PyOdide has an issue template to request new packages. Requirements are that you should try and build it yourself first. See:
 - https://github.com/pyodide/pyodide/issues/new/choose
 - https://pyodide.org/en/stable/development/building-and-testing-packages.html
