### ISSUE TITLE
Not able to create DAG in python

### ISSUE THREAD

**Issue by kimo** [PySheets/pysheets#89]
Error

![Uploading Screenshot 2024-09-29 at 11.36.50 AM.png…]()

**Code**
```
=
# This code was generated by an AI. Please check it for errors.

import matplotlib.pyplot as plt

# Define nodes
nodes = ['A', 'B', 'C', 'D', 'E', 'F']

# Define edges
edges = [('A', 'B'), ('A', 'C'), ('B', 'D'), ('C', 'D'), ('C', 'E'), ('D', 'F'), ('E', 'F')]

# Create figure and axes
fig, ax = plt.subplots(figsize=(8, 6))

# Plot nodes
for node in nodes:
    ax.scatter(node, 0, s=500, color='blue')

# Plot edges
for edge in edges:
    ax.plot([edge[0], edge[1]], [0, 0], color='black')

# Set axis limits and labels
ax.set_xlim(-0.5, len(nodes) - 0.5)
ax.set_ylim(-0.5, 0.5)
ax.set_xticks(range(len(nodes)))
ax.set_xticklabels(nodes)
ax.set_yticks([])
ax.set_xlabel('Nodes')
ax.set_title('DAG Graph')

# Show figure
fig
```

**Comment by kimo** [comment]
This is still an issue in 0.3.13

**Comment by kimo** [comment]
**DevTools Console**

'''
error 32 Line 32: pyodide.ffi.JsException: TypeError: Cannot assign to read only property 'data' of object '#<ImageData>' - Traceback (most recent call last):
  File "<exec>", line 300, in handle_run
  File "<exec>", line 287, in run_in_worker
  File "<string>", line 32, in <module>
  File "/lib/python3.12/site-packages/matplotlib/pyplot.py", line 389, in show
    return _get_backend_mod().show(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/matplotlib_pyodide/wasm_backend.py", line 117, in show
    plt.gcf().canvas.show(*args, **kwargs)
  File "/lib/python3.12/site-packages/matplotlib_pyodide/browser_backend.py", line 191, in show
    self.draw()
  File "/lib/python3.12/site-packages/matplotlib_pyodide/wasm_backend.py", line 55, in draw
    ctx.putImageData(image_data, 0, 0)
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in Object.value
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in Object.apply
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in o
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in o
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in o
pyodide.ffi.JsException: TypeError: Cannot assign to read only property 'data' of object '#<ImageData>'
 Traceback (most recent call last):
  File "<exec>", line 300, in handle_run
  File "<exec>", line 287, in run_in_worker
  File "<string>", line 32, in <module>
  File "/lib/python3.12/site-packages/matplotlib/pyplot.py", line 389, in show
    return _get_backend_mod().show(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/matplotlib_pyodide/wasm_backend.py", line 117, in show
    plt.gcf().canvas.show(*args, **kwargs)
  File "/lib/python3.12/site-packages/matplotlib_pyodide/browser_backend.py", line 191, in show
    self.draw()
  File "/lib/python3.12/site-packages/matplotlib_pyodide/wasm_backend.py", line 55, in draw
    ctx.putImageData(image_data, 0, 0)
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in Object.value
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in Object.apply
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in o
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in o
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in o
pyodide.ffi.JsException: TypeError: Cannot assign to read only property 'data' of object '#<ImageData>'

micropython.mjs:1 Traceback (most recent call last):
  File "<exec>", line 300, in handle_run
  File "<exec>", line 287, in run_in_worker
  File "<string>", line 32, in <module>
  File "/lib/python3.12/site-packages/matplotlib/pyplot.py", line 389, in show
    return _get_backend_mod().show(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/matplotlib_pyodide/wasm_backend.py", line 117, in show
    plt.gcf().canvas.show(*args, **kwargs)
  File "/lib/python3.12/site-packages/matplotlib_pyodide/browser_backend.py", line 191, in show
    self.draw()
  File "/lib/python3.12/site-packages/matplotlib_pyodide/wasm_backend.py", line 55, in draw
    ctx.putImageData(image_data, 0, 0)
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in Object.value
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in Object.apply
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in o
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in o
  File "blob:http://127.0.0.1:8081/a5c2c485-f182-4daa-aa15-d43cc96c843b", line 1, in o
pyodide.ffi.JsException: TypeError: Cannot assign to read only property 'data' of object '#<ImageData>'

pyodide.asm.js:10 Uncaught PythonError
    at new_error (pyodide.asm.js:10:9965)
    at pyodide.asm.wasm:0x16dc69
    at pyodide.asm.wasm:0x16dd2f
    at Module._pythonexc2js (pyodide.asm.js:10:698851)
    at callPyObjectKwargs (pyodide.asm.js:10:62328)
    at Module.callPyObject (pyodide.asm.js:10:63518)
    at wrapper (pyodide.asm.js:10:27149)
new_error @ pyodide.asm.js:10
$wrap_exception @ pyodide.asm.wasm:0x16dc69
$pythonexc2js @ pyodide.asm.wasm:0x16dd2f
Module._pythonexc2js @ pyodide.asm.js:10
callPyObjectKwargs @ pyodide.asm.js:10
Module.callPyObject @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10Understand this errorAI
a5c2c485-f182-4daa-aa15-d43cc96c843b:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'onerror')
    at dn (a5c2c485-f182-4daa-aa15-d43cc96c843b:1:19349)
    at Object.runEvent (a5c2c485-f182-4daa-aa15-d43cc96c843b:1:26963)
    at t.once (a5c2c485-f182-4daa-aa15-d43cc96c843b:1:33466)
dn @ a5c2c485-f182-4daa-aa15-d43cc96c843b:1
(anonymous) @ a5c2c485-f182-4daa-aa15-d43cc96c843b:1
t.once @ a5c2c485-f182-4daa-aa15-d43cc96c843b:1Understand this errorAI

'''

**Comment by kimo** [comment]
![Screenshot 2024-10-03 at 11 33 00 AM](https://github.com/user-attachments/assets/e9170cfe-f086-4ca8-9c57-cdf782c6f2f3)

**Comment by kimo** [comment]
```
# AI Prompt
# create a sample DAG graph using matplotlib without using the networkx


=
# This code was generated by an AI. Please check it for errors.

import matplotlib.pyplot as plt

# Create nodes
nodes = ['A', 'B', 'C', 'D', 'E', 'F']

# Create edges
edges = [('A', 'B'), ('A', 'C'), ('B', 'D'), ('C', 'D'), ('C', 'E'), ('D', 'F'), ('E', 'F')]

# Create figure and axes
fig, ax = plt.subplots(figsize=(8, 6))

# Plot nodes
for node in nodes:
    ax.scatter(node, 0, s=200, color='blue')

# Plot edges
for edge in edges:
    ax.plot([edge[0], edge[1]], [0, 0], color='black')

# Set axis limits and labels
ax.set_xlim(-1, len(nodes))
ax.set_ylim(-1, 1)
ax.set_xticks(range(len(nodes)))
ax.set_xticklabels(nodes)
ax.set_yticks([])
ax.set_xlabel('Nodes')
ax.set_title('Sample DAG Graph')

plt.show()

# Show figure
fig



```

**Comment by kimo** [comment]
This appears to be a pyodide problem.
